#!/usr/bin/python3
import argparse
import requests

try:
    import RPi.GPIO as IO
except ImportError:
    print(
        "No GPIO lib detected. Is this running on the PI and has this library been installed?"
    )
    quit(1)

# If custom config file is defined, use the supplied config file instead
parser = argparse.ArgumentParser(description="Pump manager")
parser.add_argument(
    "--url",
    dest="url",
    default="https://beer.tanger.dev/temp",
    required=False,
    type=str,
    help="Endpoint to send  data to",
)
args = parser.parse_args()

ONEWIRE_FILENAME = None #Change name to the file generated by onewire on the pi
if not ONEWIRE_FILENAME:
    print("Please set a filename for the onewire output")
    quit(1)

FILENAME = f"/dev/{ONEWIRE_FILENAME}"

if __name__ == "__main__":
    with open(FILENAME, "rb") as fd:
        data = fd.read()

    response = requests.post(args.url, data={"temp_reading": data})
    if response.status_code == 200:
        print(f"Templog request sent with data: {data}")
        quit(0)
    print(
        f"Templog request NOT sent successfully with data: {data} and response code: {response.status_code}"
    )
    quit(1)
