#!/usr/bin/python3
import argparse
import requests
import os

try:
    import RPi.GPIO as IO
except ImportError:
    print(
        "No GPIO lib detected. Is this running on the PI and has this library been installed?"
    )
    quit(1)

# If custom config file is defined, use the supplied config file instead
parser = argparse.ArgumentParser(description="Pump manager")
parser.add_argument(
    "--url",
    dest="url",
    default="https://beer.tanger.dev/temp",
    required=False,
    type=str,
    help="Endpoint to send  data to",
)
parser.add_argument(
    "--1w-directory",
    dest="owdn",
    default="/sys/bus/w1/devices/",
    required=False,
    type=str,
    help="Endpoint to send  data to",
)
args = parser.parse_args()

ONEWIRE_DIR = args.owdn

# Default /sys/bus/w1/devices
ONEWIRE_FILENAME = None  # Change name to the file generated by onewire on the pi

if __name__ == "__main__":
    # Check that the onewire directory hierarchy exists
    owiredir_exists = os.path.isdir(ONEWIRE_DIR)
    owirefile_exists = os.path.isfile(ONEWIRE_FILENAME)
    if not owiredir_exists or owirefile_exists:
        print(f"""
              Bad config, recheck where the onewire file is located

              If these checks are not true, check that the path is correct.
              Does Onewire parent dir exist?: {ONEWIRE_DIR}
              Does Onewire file exist?: {ONEWIRE_FILENAME}

              If this still doesn't work, check the wiring
              """)
        quit(1)

    with open(os.path.join(ONEWIRE_DIR, ONEWIRE_FILENAME), "rb") as fd:
        data = fd.read()

    response = requests.post(args.url, data={"temp_reading": data})
    if response.status_code == 200:
        print(f"Templog request sent with data: {data}")
        quit(0)
    print(
        f"Templog request NOT sent successfully with data: {data} and response code: {response.status_code}"
    )
    quit(1)
